name: Push Database Schema to Production

on:
  release:
    types: [published]

jobs:
  db-push:
    runs-on: ubuntu-latest

    # Only run on production releases (you can adjust the condition)
    if: github.event.release.prerelease == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Push database schema
        run: npm run db:push
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Notify on failure
        if: failure()
        run: echo "Database push failed! Check the logs above for details."
